const string = { type: 'string' };
const nullableString = { type: ['string', 'null'] };
const hash = { type: 'string', pattern: '^[a-fA-F0-9]{64}$' };
const record = { $ref: '#/components/schemas/Analysis' };
const response = { description: 'Persisted dataset and figure settings.', content: { 'application/json': { schema: { type: 'object', required: ['analysis'], properties: { analysis: record } } } } };
const errors = {
  '400': { description: 'Invalid dataset, coordinates, figure settings or JSON.' },
  '404': { description: 'Analysis does not exist.' },
  '409': { description: 'Revision conflict. Response includes latest analysis; preserve local edits.' },
  '413': { description: 'Request exceeds 2 MiB.' },
  '429': { description: 'Request budget exceeded; retry later.' },
};
const body = (name: string) => ({ required: true, content: { 'application/json': { schema: { $ref: `#/components/schemas/${name}` } } } });

export const analysisPaths = {
  '/api/analyses': { post: { operationId: 'createAnalysis', summary: 'Save scores, genomic tracks, splice junctions or experimental measurements with a figure recipe',
    description: 'Stores supplied numerical results without running inference. Anyone with the returned link can view and edit it. Do not upload private genomic data.',
    requestBody: body('AnalysisInput'), responses: { '201': response, ...errors } } },
  '/api/analyses/{id}': {
    parameters: [{ name: 'id', in: 'path', required: true, schema: { type: 'string', format: 'uuid' } }],
    get: { operationId: 'getAnalysis', summary: 'Read a saved analysis', responses: { '200': response, ...errors } },
    patch: { operationId: 'updateAnalysis', summary: 'Save a complete replacement at the expected revision',
      requestBody: body('AnalysisPatch'), responses: { '200': response, ...errors } },
  },
};
export const analysisSchemas = {
  AnalysisInterval: { type: 'object', additionalProperties: false, required: ['chromosome', 'start', 'end', 'coordinateSystem'],
    description: 'A nonempty interval on a primary human chromosome. End is exclusive.',
    properties: { chromosome: string, start: { type: 'integer', minimum: 0 }, end: { type: 'integer', minimum: 1 }, coordinateSystem: { const: '0-based-half-open' } } },
  AnalysisInference: { type: 'object', additionalProperties: false,
    description: 'Source-reported execution provenance. Importing this record does not authenticate or run the model. Display interval must be inside the input interval, which must contain the exact variant.',
    required: ['variant', 'inputInterval', 'displayInterval', 'modelRevision', 'clientRevision', 'checkpointRevision', 'referenceVersion', 'referenceSha256', 'transformations'],
    properties: { variant: string, inputInterval: { $ref: '#/components/schemas/AnalysisInterval' }, displayInterval: { $ref: '#/components/schemas/AnalysisInterval' },
      modelRevision: string, clientRevision: string, checkpointRevision: string, referenceVersion: string,
      referenceSha256: { anyOf: [hash, { type: 'null' }], description: 'Whole reference-file hash, or null when unavailable. Not the model input sequence hash.' },
      inputSequenceSha256: hash, transformations: { type: 'array', maxItems: 50, items: { type: 'string', minLength: 1, maxLength: 1000 } } } },
  AnalysisArtifact: { type: 'object', additionalProperties: false, required: ['filename', 'sha256'],
    description: 'Checksum of the original source artifact retained separately by the importer. The API stores this reference, not the source file.',
    properties: { filename: { type: 'string', minLength: 1, maxLength: 240, description: 'Basename only; no paths or control characters.' }, sha256: hash } },
  AnalysisProvenance: { type: 'object', additionalProperties: false,
    required: ['sourceUrl', 'sourceLabel', 'assembly', 'model', 'context', 'mode'],
    properties: { sourceUrl: { ...string, description: 'HTTP(S) source URL, or empty for user imports.' }, sourceLabel: string,
      assembly: { ...string, description: 'Explicit genome assembly. Variant syntax checks are not reference-allele validation.' }, model: string, context: string,
      recordedAt: { type: 'string', format: 'date-time' }, mode: { enum: ['published-example', 'imported'] },
      artifact: { $ref: '#/components/schemas/AnalysisArtifact' }, inference: { $ref: '#/components/schemas/AnalysisInference' } } },
  AnalysisScoreRow: { type: 'object', required: ['variant', 'biosample', 'modality', 'scorer', 'score'],
    properties: { variant: { ...string, description: 'Human primary-chromosome SNV, one-based: chr9:128226027:G>A.' }, biosample: string,
      modality: string, scorer: string, score: { type: 'number', description: 'Finite raw molecular-effect score, in scorer-specific units.' },
      quantile: { type: 'number', minimum: -1, maximum: 1, description: 'May be signed. Not a clinical probability or AVI PHRED.' },
      gene: string, track: string, unit: string, signed: { type: 'boolean' }, trackStrand: { enum: ['+', '-', '.'] },
      assay: string, sourceRowIndex: { type: 'integer', minimum: 0 }, scoredInterval: string, geneId: string, geneStrand: { enum: ['+', '-', '.'] }, histoneMark: string },
    additionalProperties: false },
  AnalysisTrackRow: { type: 'object', additionalProperties: false, required: ['chromosome', 'position', 'reference', 'alternate', 'track'],
    properties: { chromosome: { ...string, description: 'Primary human chromosome, e.g. chr9.' },
      position: { type: 'integer', minimum: 0, description: 'Zero-based genomic coordinate. Must be unique per chromosome and track.' },
      reference: { type: 'number', description: 'Reference signal value.' }, alternate: { type: 'number', description: 'Alternate signal value.' }, track: string } },
  AnalysisTrackMetadata: { type: 'object', additionalProperties: false,
    description: 'Optional metadata for one unique chromosome/track pair present in rows. Declared bins must align and fit the chromosome and recorded display interval. Missing fields are not inferred.',
    required: ['chromosome', 'track', 'outputType', 'unit', 'strand', 'biosampleId', 'biosampleName', 'scope', 'binSize'],
    properties: { chromosome: string, track: string, outputType: string, unit: nullableString, strand: { enum: ['+', '-', '.', null] },
      biosampleId: nullableString, biosampleName: nullableString, scope: { enum: ['biosample_specific', 'tissue_agnostic', 'unspecified'], description: 'Tissue-agnostic tracks must have null biosample identifiers and names.' },
      binSize: { type: 'integer', minimum: 1 }, sourceName: string, sourceIndex: { type: 'integer', minimum: 0 } } },
  AnalysisJunctionRow: { type: 'object', additionalProperties: false,
    description: 'A unique chromosome/start/end/strand/track junction. Endpoints are ascending zero-based half-open genomic coordinates on both strands. The arc must overlap the dataset display interval; spanning endpoints are retained within the inference input interval when supplied. At least one allele must be nonnull; null is unavailable, never zero. Values are signals, not probabilities.',
    required: ['chromosome', 'start', 'end', 'strand', 'track', 'reference', 'alternate'],
    properties: { chromosome: string, start: { type: 'integer', minimum: 0, maximum: Number.MAX_SAFE_INTEGER },
      end: { type: 'integer', minimum: 1, maximum: Number.MAX_SAFE_INTEGER, description: 'Exclusive end must exceed start.' }, strand: { enum: ['+', '-'] }, track: string,
      reference: { type: ['number', 'null'], minimum: 0 }, alternate: { type: ['number', 'null'], minimum: 0 } },
    anyOf: [{ properties: { reference: { type: 'number', minimum: 0 } } }, { properties: { alternate: { type: 'number', minimum: 0 } } }] },
  AnalysisJunctionTrackMetadata: { type: 'object', additionalProperties: false,
    description: 'Required exhaustive metadata for every chromosome/track pair in junction rows; no duplicate pairs or orphan metadata. This is not a fixed-width bin, so binSize is forbidden. A strand-specific metadata value must match each corresponding row strand.',
    required: ['chromosome', 'track', 'outputType', 'unit', 'strand', 'biosampleId', 'biosampleName', 'scope'],
    properties: { chromosome: string, track: string, outputType: { const: 'SPLICE_JUNCTIONS' }, unit: nullableString, strand: { enum: ['+', '-', '.', null] },
      biosampleId: nullableString, biosampleName: nullableString, scope: { enum: ['biosample_specific', 'tissue_agnostic', 'unspecified'], description: 'Tissue-agnostic requires null biosample identifiers and names; biosample-specific requires a name or identifier.' },
      sourceName: string, sourceIndex: { type: 'integer', minimum: 0, maximum: Number.MAX_SAFE_INTEGER } } },
  AnalysisExperiment: { type: 'object', additionalProperties: false,
    description: 'One comparable experimental assay and condition aggregate. These are measured values, not model predictions. Retain the reported aggregation and replicate policy.',
    required: ['assay', 'endpoint', 'unit', 'unitLabel', 'aggregation', 'conditions', 'replicatePolicy', 'sourceLocator'],
    properties: { assay: string, endpoint: string, unit: { enum: ['fraction', 'percent', 'count', 'arbitrary'] }, unitLabel: string,
      aggregation: string, conditions: { type: 'array', minItems: 1, items: string }, replicatePolicy: string, sourceLocator: string } },
  AnalysisMeasurementRow: { type: 'object', additionalProperties: false,
    description: 'One measured value per exact variant. Fraction values must be 0–1; percentages 0–100; counts nonnegative. Null replicate count and standard error mean unavailable, never zero. Reported text must equal the numeric value.',
    required: ['variant', 'value', 'replicates', 'standardError'],
    properties: { variant: string, gene: string, value: { type: 'number' }, reportedValue: string,
      replicates: { type: ['integer', 'null'], minimum: 1 }, standardError: { type: ['number', 'null'], minimum: 0 }, sourceRowIndex: { type: 'integer', minimum: 0 } } },
  AnalysisDataset: { oneOf: ['scores', 'tracks', 'measurements', 'junctions'].map(kind => ({ type: 'object', additionalProperties: false,
    required: ['schemaVersion', 'id', 'title', 'kind', 'provenance', 'rows', ...(kind === 'measurements' ? ['experiment'] : []), ...(kind === 'junctions' ? ['interval', 'trackMetadata'] : [])],
    properties: { schemaVersion: { const: 1 }, id: string, title: string, kind: { const: kind },
      provenance: { $ref: '#/components/schemas/AnalysisProvenance' },
      ...(kind === 'tracks' ? { trackMetadata: { type: 'array', maxItems: 5000, items: { $ref: '#/components/schemas/AnalysisTrackMetadata' } } } : {}),
      ...(kind === 'junctions' ? { interval: { $ref: '#/components/schemas/AnalysisInterval', description: 'Display interval; must equal inference.displayInterval when execution provenance is supplied.' },
        variant: { ...string, description: 'Optional exact one-based SNV on the interval chromosome. Must equal inference.variant when both exist; it does not assert model execution.' },
        trackMetadata: { type: 'array', minItems: 1, maxItems: 5000, items: { $ref: '#/components/schemas/AnalysisJunctionTrackMetadata' } } } : {}),
      ...(kind === 'measurements' ? { experiment: { $ref: '#/components/schemas/AnalysisExperiment' } } : {}),
      rows: { type: 'array', minItems: 1, maxItems: 5000, items: { $ref: `#/components/schemas/Analysis${kind === 'scores' ? 'Score' : kind === 'tracks' ? 'Track' : kind === 'junctions' ? 'Junction' : 'Measurement'}Row` } } } })) },
  FigureSettings: { type: 'object', additionalProperties: false,
    required: ['chart', 'title', 'modality', 'scorer', 'track', 'gene', 'metric', 'limit', 'variant'],
    properties: { chart: { enum: ['bars', 'heatmap', 'tracks', 'junctions', 'table'] }, title: string, modality: string, scorer: string, track: string,
      gene: string, metric: { enum: ['score', 'quantile'] }, limit: { type: 'integer', minimum: 1, maximum: 100 }, variant: string } },
  AnalysisInput: { type: 'object', additionalProperties: false, required: ['dataset', 'settings'], properties: {
    dataset: { $ref: '#/components/schemas/AnalysisDataset' }, settings: { $ref: '#/components/schemas/FigureSettings' } },
    description: 'Experimental measurements support bars (dot plot) or table with the score metric used as the measured value; no model quantiles or inference provenance. Junction datasets support junctions or table with score selecting supplied REF/ALT signals; no quantile interpretation. Other dataset kinds cannot select junctions.' },
  AnalysisPatch: { type: 'object', additionalProperties: false, required: ['revision', 'dataset', 'settings'], properties: {
    revision: { type: 'integer', minimum: 0 }, dataset: { $ref: '#/components/schemas/AnalysisDataset' }, settings: { $ref: '#/components/schemas/FigureSettings' } } },
  Analysis: { type: 'object', required: ['id', 'revision', 'dataset', 'settings', 'createdAt', 'updatedAt'], properties: {
    id: { type: 'string', format: 'uuid' }, revision: { type: 'integer', minimum: 0 }, dataset: { $ref: '#/components/schemas/AnalysisDataset' },
    settings: { $ref: '#/components/schemas/FigureSettings' }, createdAt: { type: 'string', format: 'date-time' }, updatedAt: { type: 'string', format: 'date-time' } } },
};
